/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class Queue {
  constructor()
  push(val: number): void
  pop(): number | null
  peek(): number | null
  len(): number
  isEmpty(): boolean
}
